In [1]:
import pandas as pd

In [23]:
import urllib
import requests

In [73]:
from ddf_utils.str import to_concept_id

In [3]:
!ls ../source/

unhcr_popstats_export_demographics_all_data.csv
unhcr_popstats_export_time_series_all_data.csv

In [8]:
!head ../source/unhcr_popstats_export_time_series_all_data.csv

In [131]:
!cat ../source/unhcr_popstats_export_time_series_all_data.csv | grep "*" | tail

In [224]:
data = pd.read_csv('../source/unhcr_popstats_export_time_series_all_data.csv', 
                   encoding='latin', skiprows=3, na_values=['*'])

In [86]:
data.head()

,Year,Country / territory of asylum/residence,Origin,Population type,Value
0,1951,Australia,Various/Unknown,Refugees (incl. refugee-like situations),180000
1,1951,Austria,Various/Unknown,Refugees (incl. refugee-like situations),282000
2,1951,Belgium,Various/Unknown,Refugees (incl. refugee-like situations),55000
3,1951,Canada,Various/Unknown,Refugees (incl. refugee-like situations),168511
4,1951,"China, Hong Kong SAR",Various/Unknown,Refugees (incl. refugee-like situations),30000

In [15]:
data['Origin'].unique()

array(['Various/Unknown', 'Angola', 'Rwanda', 'Ghana', 'Sudan',
       'Guinea-Bissau', 'Dem. Rep. of the Congo', 'Viet Nam', 'China',
       'Albania', 'Armenia', 'Russian Federation', 'Tibetan',
       'Mozambique', 'Congo', 'Burundi', 'Greece', 'Hungary',
       'Cabo Verde', 'Malawi', 'Namibia', 'South Africa', 'Ethiopia',
       'Zambia', 'Nigeria', 'Iraq', 'Syrian Arab Rep.', 'Bulgaria',
       'Serbia and Kosovo (S/RES/1244 (1999))', 'Cuba', 'Chad', 'Romania',
       'Czech Rep.', 'Poland', 'Spain',
       'Bolivia (Plurinational State of)', 'Lesotho', 'Brazil', 'Guinea',
       'India', 'Cambodia', 'Myanmar', 'Turkey', 'Uganda', 'Chile',
       'Uruguay', 'Pakistan', 'Haiti', 'United Rep. of Tanzania',
       'Equatorial Guinea', 'Western Sahara', 'Zimbabwe',
       "Lao People's Dem. Rep.", 'Kenya', 'Somalia', 'Palestinian',
       'Benin', 'Cyprus', 'Philippines', 'Nicaragua', 'Egypt',
       'Dominican Rep.', 'Indonesia', 'Yemen', 'Afghanistan', 'Eritrea',
       'El Salvador', 'Guatemala', 'Algeria', 'Argentina',
       'Iran (Islamic Rep. of)', 'Libya', 'Lithuania', 'Stateless',
       'Tunisia', 'Colombia', 'Central African Rep.', 'Lebanon', 'Jordan',
       'Morocco', 'Seychelles', 'Burkina Faso', 'Mauritania', 'Togo',
       'Sao Tome and Principe', 'Sri Lanka', 'Honduras', 'Bangladesh',
       "CÃ´te d'Ivoire", 'Israel', 'Liberia', 'Senegal', 'Gambia',
       'Grenada', 'Guyana', 'Maldives', 'Malta', 'Peru', 'Sierra Leone',
       'Singapore', 'Panama', 'Cameroon', 'Botswana', 'Comoros',
       'Thailand', 'Suriname', 'Bahrain', 'Kuwait', 'Ecuador', 'Mali',
       'Mongolia', 'Paraguay', 'Trinidad and Tobago', 'United Kingdom',
       'United States of America', 'Djibouti', 'Fiji', 'Costa Rica',
       'Bhutan', 'Canada', 'Estonia', 'Germany', 'Madagascar', 'Malaysia',
       'Niger', 'Venezuela (Bolivarian Republic of)', 'Rep. of Korea',
       'Tajikistan', 'Azerbaijan', 'Kazakhstan', 'Ukraine',
       'Bosnia and Herzegovina', 'China, Hong Kong SAR', 'Croatia',
       'French Guiana', 'Italy', 'Nepal', 'Gabon', 'Latvia', 'Georgia',
       'Rep. of Moldova', 'Saudi Arabia', 'Jamaica', 'Slovenia',
       'The former Yugoslav Republic of Macedonia', 'Kyrgyzstan',
       'Belarus', 'Uzbekistan', 'Swaziland', 'Andorra', 'Australia',
       'Austria', 'Barbados', 'Belgium', 'Belize',
       "Dem. People's Rep. of Korea", 'Denmark', 'France', 'Ireland',
       'Japan', 'Mauritius', 'Mexico', 'Netherlands', 'Norway', 'Oman',
       'Portugal', 'Puerto Rico', 'Qatar',
       'Saint Vincent and the Grenadines', 'Samoa', 'Slovakia', 'Sweden',
       'Switzerland', 'Turkmenistan', 'Finland', 'Saint Lucia',
       'Martinique', 'Solomon Islands', 'Tuvalu', 'Papua New Guinea',
       'Brunei Darussalam', 'Tonga', 'Iceland', 'China, Macao SAR',
       'Dominica', 'Monaco', 'United Arab Emirates',
       'Antigua and Barbuda', 'San Marino', 'Bermuda', 'Bahamas',
       'Timor-Leste', 'Nauru', 'Vanuatu', 'Saint Kitts and Nevis',
       'New Zealand', 'Palau', 'Kiribati',
       'Micronesia (Federated States of)', 'Cayman Islands', 'Gibraltar',
       'Marshall Islands', 'Turks and Caicos Islands', 'Luxembourg',
       'French Polynesia', 'Niue', 'Holy See (the)', 'New Caledonia',
       'Montenegro', 'Cook Islands', 'Aruba', 'Liechtenstein',
       'South Sudan', 'CuraÃ§ao', 'British Virgin Islands', 'Anguilla',
       'Norfolk Island', 'Wallis and Futuna Islands ', 'Guadeloupe',
       'Saint-Pierre-et-Miquelon', 'Svalbard and Jan Mayen',
       'American Samoa', 'Guam', "CÃÂ´te d'Ivoire", 'CuraÃÂ§ao'],
      dtype=object)

In [17]:
data['Country / territory of asylum/residence'].unique()

array(['Australia', 'Austria', 'Belgium', 'Canada',
       'China, Hong Kong SAR', 'Denmark', 'France', 'Germany', 'Greece',
       'Italy', 'Luxembourg', 'Morocco', 'Netherlands', 'Norway', 'Spain',
       'Sweden', 'Switzerland', 'Tunisia', 'Turkey', 'United Kingdom',
       'United States of America', 'Various/Unknown',
       'Dem. Rep. of the Congo', 'Burundi', 'Togo', 'Uganda',
       'United Rep. of Tanzania', 'Iran (Islamic Rep. of)', 'Senegal',
       'Cambodia', 'Central African Rep.', 'China, Macao SAR', 'Egypt',
       'India', 'Lebanon', 'Nepal', 'Rwanda',
       'Serbia and Kosovo (S/RES/1244 (1999))', 'Zambia', 'Bhutan',
       'China', 'New Zealand', 'Sudan', 'Botswana', 'Cyprus',
       'Equatorial Guinea', 'Ethiopia', 'United Arab Emirates',
       'Argentina', 'Benin', 'Brazil', 'Chile', 'Congo', "CÃ´te d'Ivoire",
       'Gabon', 'Ghana', 'Liberia', 'Paraguay', 'Sierra Leone',
       'Venezuela (Bolivarian Republic of)', 'Algeria', 'Cameroon',
       'Colombia', 'Dominican Rep.', 'Kenya', 'Lesotho', 'Mexico', 'Peru',
       'Swaziland', 'Uruguay', 'Jordan', 'Mali', 'Viet Nam',
       'Bolivia (Plurinational State of)', 'Costa Rica', 'Ecuador',
       'El Salvador', 'Guatemala', 'Guyana', 'Honduras',
       "Lao People's Dem. Rep.", 'Nicaragua', 'Panama', 'Bahrain',
       'Bangladesh', 'Cuba', 'Saudi Arabia', 'Gambia', 'Mozambique',
       'Philippines', 'Portugal', 'Thailand', 'Angola', 'Nigeria',
       'Djibouti', 'Japan', 'Malaysia', 'Niger', 'Romania', 'Somalia',
       'Yemen', 'Indonesia', 'Papua New Guinea', 'Rep. of Korea',
       'Singapore', 'Syrian Arab Rep.', 'Iraq', 'Kuwait', 'Pakistan',
       'Belize', 'Qatar', 'Zimbabwe', 'Guinea-Bissau', 'Burkina Faso',
       'Finland', 'Ireland', 'Malawi', 'Mauritania', 'French Guiana',
       'Hungary', 'Afghanistan', 'Comoros', 'Guinea', 'Iceland',
       'Cabo Verde', 'Czech Rep.', 'Jamaica', 'Namibia', 'Poland',
       'Sri Lanka', 'Albania', 'Armenia', 'Azerbaijan', 'Bahamas',
       'Bulgaria', 'Chad', 'Croatia', 'Slovenia', 'Suriname',
       'Tajikistan', 'The former Yugoslav Republic of Macedonia',
       'Bosnia and Herzegovina', 'Eritrea', 'Georgia', 'Kazakhstan',
       'Kyrgyzstan', 'Libya', 'Malta', 'Russian Federation', 'Slovakia',
       'South Africa', 'Turkmenistan', 'Uzbekistan', 'Belarus',
       'Madagascar', 'Ukraine', 'Fiji', 'Solomon Islands', 'Lithuania',
       'Rep. of Moldova', 'Saint Lucia', 'Israel', 'Latvia', 'Haiti',
       'Mauritius', 'Estonia', 'Liechtenstein', 'Oman', 'Palestinian',
       'Timor-Leste', 'Mongolia', 'Myanmar',
       'Micronesia (Federated States of)', 'Montenegro',
       'Antigua and Barbuda', 'Trinidad and Tobago', 'Vanuatu',
       'British Virgin Islands', 'Cayman Islands', 'Palau',
       'Saint Vincent and the Grenadines', 'Aruba', 'Bonaire',
       'Brunei Darussalam', 'CuraÃ§ao', 'Grenada', 'Monaco', 'Montserrat',
       'Sint Maarten (Dutch part)', 'Tonga', 'South Sudan', 'Barbados',
       'Nauru', 'Saint Kitts and Nevis', 'Turks and Caicos Islands',
       'Anguilla', "Dem. People's Rep. of Korea", 'Samoa', 'Seychelles',
       "CÃÂ´te d'Ivoire", 'CuraÃÂ§ao', 'Maldives', 'State of Palestine'],
      dtype=object)

In [18]:
seta = set(data['Country / territory of asylum/residence'].unique())
setb = set(data['Origin'].unique())

seta.difference(setb)

{'Bonaire', 'Montserrat', 'Sint Maarten (Dutch part)', 'State of Palestine'}

In [20]:
all_countries = setb.union(seta)

In [21]:
all_countries

{'Afghanistan',
 'Albania',
 'Algeria',
 'American Samoa',
 'Andorra',
 'Angola',
 'Anguilla',
 'Antigua and Barbuda',
 'Argentina',
 'Armenia',
 'Aruba',
 'Australia',
 'Austria',
 'Azerbaijan',
 'Bahamas',
 'Bahrain',
 'Bangladesh',
 'Barbados',
 'Belarus',
 'Belgium',
 'Belize',
 'Benin',
 'Bermuda',
 'Bhutan',
 'Bolivia (Plurinational State of)',
 'Bonaire',
 'Bosnia and Herzegovina',
 'Botswana',
 'Brazil',
 'British Virgin Islands',
 'Brunei Darussalam',
 'Bulgaria',
 'Burkina Faso',
 'Burundi',
 'Cabo Verde',
 'Cambodia',
 'Cameroon',
 'Canada',
 'Cayman Islands',
 'Central African Rep.',
 'Chad',
 'Chile',
 'China',
 'China, Hong Kong SAR',
 'China, Macao SAR',
 'Colombia',
 'Comoros',
 'Congo',
 'Cook Islands',
 'Costa Rica',
 'Croatia',
 'Cuba',
 'CuraÃÂ§ao',
 'CuraÃ§ao',
 'Cyprus',
 'Czech Rep.',
 "CÃÂ´te d'Ivoire",
 "CÃ´te d'Ivoire",
 "Dem. People's Rep. of Korea",
 'Dem. Rep. of the Congo',
 'Denmark',
 'Djibouti',
 'Dominica',
 'Dominican Rep.',
 'Ecuador',
 'Egypt',
 'El Salvador',
 'Equatorial Guinea',
 'Eritrea',
 'Estonia',
 'Ethiopia',
 'Fiji',
 'Finland',
 'France',
 'French Guiana',
 'French Polynesia',
 'Gabon',
 'Gambia',
 'Georgia',
 'Germany',
 'Ghana',
 'Gibraltar',
 'Greece',
 'Grenada',
 'Guadeloupe',
 'Guam',
 'Guatemala',
 'Guinea',
 'Guinea-Bissau',
 'Guyana',
 'Haiti',
 'Holy See (the)',
 'Honduras',
 'Hungary',
 'Iceland',
 'India',
 'Indonesia',
 'Iran (Islamic Rep. of)',
 'Iraq',
 'Ireland',
 'Israel',
 'Italy',
 'Jamaica',
 'Japan',
 'Jordan',
 'Kazakhstan',
 'Kenya',
 'Kiribati',
 'Kuwait',
 'Kyrgyzstan',
 "Lao People's Dem. Rep.",
 'Latvia',
 'Lebanon',
 'Lesotho',
 'Liberia',
 'Libya',
 'Liechtenstein',
 'Lithuania',
 'Luxembourg',
 'Madagascar',
 'Malawi',
 'Malaysia',
 'Maldives',
 'Mali',
 'Malta',
 'Marshall Islands',
 'Martinique',
 'Mauritania',
 'Mauritius',
 'Mexico',
 'Micronesia (Federated States of)',
 'Monaco',
 'Mongolia',
 'Montenegro',
 'Montserrat',
 'Morocco',
 'Mozambique',
 'Myanmar',
 'Namibia',
 'Nauru',
 'Nepal',
 'Netherlands',
 'New Caledonia',
 'New Zealand',
 'Nicaragua',
 'Niger',
 'Nigeria',
 'Niue',
 'Norfolk Island',
 'Norway',
 'Oman',
 'Pakistan',
 'Palau',
 'Palestinian',
 'Panama',
 'Papua New Guinea',
 'Paraguay',
 'Peru',
 'Philippines',
 'Poland',
 'Portugal',
 'Puerto Rico',
 'Qatar',
 'Rep. of Korea',
 'Rep. of Moldova',
 'Romania',
 'Russian Federation',
 'Rwanda',
 'Saint Kitts and Nevis',
 'Saint Lucia',
 'Saint Vincent and the Grenadines',
 'Saint-Pierre-et-Miquelon',
 'Samoa',
 'San Marino',
 'Sao Tome and Principe',
 'Saudi Arabia',
 'Senegal',
 'Serbia and Kosovo (S/RES/1244 (1999))',
 'Seychelles',
 'Sierra Leone',
 'Singapore',
 'Sint Maarten (Dutch part)',
 'Slovakia',
 'Slovenia',
 'Solomon Islands',
 'Somalia',
 'South Africa',
 'South Sudan',
 'Spain',
 'Sri Lanka',
 'State of Palestine',
 'Stateless',
 'Sudan',
 'Suriname',
 'Svalbard and Jan Mayen',
 'Swaziland',
 'Sweden',
 'Switzerland',
 'Syrian Arab Rep.',
 'Tajikistan',
 'Thailand',
 'The former Yugoslav Republic of Macedonia',
 'Tibetan',
 'Timor-Leste',
 'Togo',
 'Tonga',
 'Trinidad and Tobago',
 'Tunisia',
 'Turkey',
 'Turkmenistan',
 'Turks and Caicos Islands',
 'Tuvalu',
 'Uganda',
 'Ukraine',
 'United Arab Emirates',
 'United Kingdom',
 'United Rep. of Tanzania',
 'United States of America',
 'Uruguay',
 'Uzbekistan',
 'Vanuatu',
 'Various/Unknown',
 'Venezuela (Bolivarian Republic of)',
 'Viet Nam',
 'Wallis and Futuna Islands ',
 'Western Sahara',
 'Yemen',
 'Zambia',
 'Zimbabwe'}

In [22]:
c = 'Venezuela (Bolivarian Republic of)'

In [33]:
url = 'https://restcountries.eu/rest/v2/name/'
url_query = url + urllib.parse.quote(c)

In [34]:
url_query

'https://restcountries.eu/rest/v2/name/Venezuela%20%28Bolivarian%20Republic%20of%29'

In [35]:
res = requests.get(url_query).json()

In [36]:
res

[{'name': 'Venezuela (Bolivarian Republic of)',
  'topLevelDomain': ['.ve'],
  'alpha2Code': 'VE',
  'alpha3Code': 'VEN',
  'callingCodes': ['58'],
  'capital': 'Caracas',
  'altSpellings': ['VE',
   'Bolivarian Republic of Venezuela',
   'RepÃºblica Bolivariana de Venezuela'],
  'region': 'Americas',
  'subregion': 'South America',
  'population': 31028700,
  'latlng': [8.0, -66.0],
  'demonym': 'Venezuelan',
  'area': 916445.0,
  'gini': 44.8,
  'timezones': ['UTC-04:00'],
  'borders': ['BRA', 'COL', 'GUY'],
  'nativeName': 'Venezuela',
  'numericCode': '862',
  'currencies': [{'code': 'VEF',
    'name': 'Venezuelan bolÃ­var',
    'symbol': 'Bs F'}],
  'languages': [{'iso639_1': 'es',
    'iso639_2': 'spa',
    'name': 'Spanish',
    'nativeName': 'EspaÃ±ol'}],
  'translations': {'de': 'Venezuela',
   'es': 'Venezuela',
   'fr': 'Venezuela',
   'ja': 'ãããºã¨ã©ã»ããªãã«å±åå½',
   'it': 'Venezuela',
   'br': 'Venezuela',
   'pt': 'Venezuela',
   'nl': 'Venezuela',
   'hr': 'Venezuela',
   'fa': 'ÙÙØ²ÙØ¦ÙØ§'},
  'flag': 'https://restcountries.eu/data/ven.svg',
  'regionalBlocs': [{'acronym': 'USAN',
    'name': 'Union of South American Nations',
    'otherAcronyms': ['UNASUR', 'UNASUL', 'UZAN'],
    'otherNames': ['UniÃ³n de Naciones Suramericanas',
     'UniÃ£o de NaÃ§Ãµes Sul-Americanas',
     'Unie van Zuid-Amerikaanse Naties',
     'South American Union']}],
  'cioc': 'VEN'}]

In [44]:
for c in all_countries:
    print(c)
    if 'Serbia and Kosovo' in c:
        print('Serbia and Kosovo')
        continue
    if 'Various' in c:
        print('various_unknown')
        continue
    url_query = url + urllib.parse.quote(c)
    respond = requests.get(url_query)
    try:
        res = respond.json()
    except:
        print(url_query)
        print(respond.content)
        raise
    if isinstance(res, dict) and res['status'] == 404:
        print(f"not found")
        continue
    if isinstance(res, list): 
        if len(res) > 1:
            print(f"multiple found:")
            for r in res:
                print(r['alpha3Code'])
        else:
            print(res[0]['alpha3Code'])

Serbia and Kosovo (S/RES/1244 (1999))
Serbia and Kosovo
Bosnia and Herzegovina
BIH
South Africa
ZAF
Lithuania
LTU
Italy
ITA
India
multiple found:
IOT
IND
Paraguay
PRY
Nicaragua
NIC
Norway
NOR
Burundi
BDI
Lebanon
LBN
State of Palestine
PSE
Nauru
NRU
Hungary
HUN
Saint Vincent and the Grenadines
VCT
Turkmenistan
TKM
Sudan
multiple found:
SSD
SDN
Bahrain
BHR
Malaysia
MYS
Timor-Leste
TLS
Denmark
DNK
Marshall Islands
MHL
Pakistan
PAK
Netherlands
NLD
Turks and Caicos Islands
TCA
Slovakia
SVK
Dominica
multiple found:
DMA
DOM
Madagascar
MDG
Kyrgyzstan
KGZ
Anguilla
AIA
Honduras
HND
Congo
multiple found:
COG
COD
El Salvador
SLV
China
multiple found:
CHN
MAC
TWN
Saint Kitts and Nevis
KNA
Papua New Guinea
PNG
Saint-Pierre-et-Miquelon
SPM
Benin
BEN
New Caledonia
NCL
Finland
FIN
Singapore
SGP
Sao Tome and Principe
STP
Senegal
SEN
Tonga
TON
Bulgaria
BGR
Gabon
GAB
Barbados
BRB
Algeria
DZA
Dem. People's Rep. of Korea
not found
United Rep. of Tanzania
not found
Central African Rep.
not found
Kuwait
KWT
Botswana
BWA
Mali
multiple found:
MLI
SOM
Albania
ALB
Iceland
ISL
Rep. of Korea
not found
Montserrat
MSR
Mexico
MEX
Kazakhstan
KAZ
Yemen
YEM
Guinea-Bissau
GNB
United States of America
USA
Chad
TCD
Japan
JPN
Palau
PLW
Namibia
NAM
Brazil
BRA
Norfolk Island
NFK
Trinidad and Tobago
TTO
Nepal
NPL
Togo
TGO
Eritrea
ERI
Comoros
COM
Mongolia
MNG
Antigua and Barbuda
ATG
Argentina
ARG
Bahamas
BHS
Ecuador
ECU
Sweden
SWE
Malawi
MWI
Jamaica
JAM
Svalbard and Jan Mayen
SJM
Turkey
TUR
Bonaire
BES
Myanmar
MMR
Swaziland
SWZ
Niue
NIU
China, Macao SAR
not found
Colombia
COL
Sint Maarten (Dutch part)
SXM
Georgia
multiple found:
GEO
SGS
Cuba
CUB
Haiti
HTI
Tibetan
not found
Stateless
not found
Liechtenstein
LIE
Panama
PAN
Cameroon
CMR
Uganda
UGA
Dem. Rep. of the Congo
not found
Various/Unknown
various_unknown
Armenia
ARM
Fiji
FJI
Western Sahara
ESH
Samoa
multiple found:
ASM
WSM
Syrian Arab Rep.
not found
Tajikistan
TJK
Afghanistan
AFG
Bermuda
BMU
Bhutan
BTN
Iraq
IRQ
Russian Federation
RUS
Somalia
SOM
CÃÂ´te d'Ivoire
not found
Cyprus
CYP
Dominican Rep.
not found
Uzbekistan
UZB
Solomon Islands
SLB
American Samoa
ASM
Poland
POL
CÃ´te d'Ivoire
CIV
Venezuela (Bolivarian Republic of)
VEN
Tunisia
TUN
United Kingdom
GBR
Belize
BLZ
Brunei Darussalam
BRN
Guyana
GUY
Guam
GUM
Rep. of Moldova
not found
Guatemala
GTM
Portugal
PRT
Holy See (the)
not found
Costa Rica
CRI
Wallis and Futuna Islands
not found
Austria
AUT
Cambodia
KHM
Uruguay
URY
Ukraine
UKR
Morocco
MAR
Indonesia
IDN
Ethiopia
ETH
China, Hong Kong SAR
not found
Maldives
MDV
United Arab Emirates
ARE
Sierra Leone
SLE
Estonia
EST
CuraÃÂ§ao
not found
Sri Lanka
LKA
Malta
MLT
Saint Lucia
LCA
Mozambique
MOZ
Slovenia
SVN
Jordan
JOR
Bolivia (Plurinational State of)
BOL
Guinea
multiple found:
GNQ
GIN
GNB
PNG
British Virgin Islands
not found
Djibouti
DJI
Equatorial Guinea
GNQ
French Polynesia
PYF
Australia
AUS
Gibraltar
GIB
Ireland
multiple found:
IRL
GBR
Monaco
MCO
Chile
CHL
Martinique
MTQ
Aruba
ABW
Latvia
LVA
Spain
ESP
Seychelles
SYC
Azerbaijan
AZE
Niger
multiple found:
NER
NGA
Tuvalu
TUV
Thailand
THA
Viet Nam
VNM
Nigeria
NGA
Iran (Islamic Rep. of)
not found
Croatia
HRV
Suriname
SUR
Cayman Islands
CYM
French Guiana
GUF
France
FRA
Saudi Arabia
SAU
Cabo Verde
CPV
Philippines
PHL
Ghana
GHA
Liberia
LBR
Cook Islands
COK
Zimbabwe
ZWE
Burkina Faso
BFA
Vanuatu
VUT
Germany
DEU
South Sudan
SSD
New Zealand
NZL
Palestinian
not found
Puerto Rico
PRI
San Marino
SMR
Rwanda
RWA
Libya
LBY
Belgium
BEL
Luxembourg
LUX
Belarus
BLR
Lesotho
LSO
Lao People's Dem. Rep.
not found
Egypt
EGY
Switzerland
CHE
Mauritius
MUS
Guadeloupe
GLP
Greece
GRC
Israel
ISR
Andorra
AND
Oman
multiple found:
OMN
ROU
Gambia
GMB
Montenegro
MNE
Romania
ROU
CuraÃ§ao
CUW
Mauritania
MRT
Grenada
GRD
Kenya
KEN
Qatar
QAT
Kiribati
KIR
Bangladesh
BGD
Peru
PER
Canada
CAN
Zambia
ZMB
The former Yugoslav Republic of Macedonia
not found
Angola
AGO
Czech Rep.
not found
Micronesia (Federated States of)
FSM

In [59]:
synonyms = pd.read_csv(
    '/Users/semio/src/work/Gapminder/datasets/open-numbers/ddf--open_numbers/'
    'ddf--synonyms--geo.csv')

In [60]:
syndict = synonyms.set_index('synonym')['geo'].to_dict()

In [67]:
other_dict = {
    'Serbia and Kosovo (S/RES/1244 (1999))': 'serbia_kosovo',
    'Bonaire': 'bonaire',
    'Stateless': 'stateless',
    'Various/Unknown': 'various_unknown',
    'Tibetan': 'tibetan'
}

In [68]:
countrymapping = dict()

In [69]:
for c in all_countries:
    c_ = c.strip()
    m = syndict.get(c_, None)
    if m is None:
        m = other_dict[c_]
        
    countrymapping[c_] = m

In [70]:
countrymapping

{'Serbia and Kosovo (S/RES/1244 (1999))': 'serbia_kosovo',
 'Bosnia and Herzegovina': 'bih',
 'South Africa': 'zaf',
 'Lithuania': 'ltu',
 'Italy': 'ita',
 'India': 'ind',
 'Paraguay': 'pry',
 'Nicaragua': 'nic',
 'Norway': 'nor',
 'Burundi': 'bdi',
 'Lebanon': 'lbn',
 'State of Palestine': 'pse',
 'Nauru': 'nru',
 'Hungary': 'hun',
 'Saint Vincent and the Grenadines': 'vct',
 'Turkmenistan': 'tkm',
 'Sudan': 'sdn',
 'Bahrain': 'bhr',
 'Malaysia': 'mys',
 'Timor-Leste': 'tls',
 'Denmark': 'dnk',
 'Marshall Islands': 'mhl',
 'Pakistan': 'pak',
 'Netherlands': 'nld',
 'Turks and Caicos Islands': 'tca',
 'Slovakia': 'svk',
 'Dominica': 'dma',
 'Madagascar': 'mdg',
 'Kyrgyzstan': 'kgz',
 'Anguilla': 'aia',
 'Honduras': 'hnd',
 'Congo': 'cog',
 'El Salvador': 'slv',
 'China': 'chn',
 'Saint Kitts and Nevis': 'kna',
 'Papua New Guinea': 'png',
 'Saint-Pierre-et-Miquelon': 'spm',
 'Benin': 'ben',
 'New Caledonia': 'ncl',
 'Finland': 'fin',
 'Singapore': 'sgp',
 'Sao Tome and Principe': 'stp',
 'Senegal': 'sen',
 'Tonga': 'ton',
 'Bulgaria': 'bgr',
 'Gabon': 'gab',
 'Barbados': 'brb',
 'Algeria': 'dza',
 "Dem. People's Rep. of Korea": 'prk',
 'United Rep. of Tanzania': 'tza',
 'Central African Rep.': 'caf',
 'Kuwait': 'kwt',
 'Botswana': 'bwa',
 'Mali': 'mli',
 'Albania': 'alb',
 'Iceland': 'isl',
 'Rep. of Korea': 'kor',
 'Montserrat': 'msr',
 'Mexico': 'mex',
 'Kazakhstan': 'kaz',
 'Yemen': 'yem',
 'Guinea-Bissau': 'gnb',
 'United States of America': 'usa',
 'Chad': 'tcd',
 'Japan': 'jpn',
 'Palau': 'plw',
 'Namibia': 'nam',
 'Brazil': 'bra',
 'Norfolk Island': 'nfk',
 'Trinidad and Tobago': 'tto',
 'Nepal': 'npl',
 'Togo': 'tgo',
 'Eritrea': 'eri',
 'Comoros': 'com',
 'Mongolia': 'mng',
 'Antigua and Barbuda': 'atg',
 'Argentina': 'arg',
 'Bahamas': 'bhs',
 'Ecuador': 'ecu',
 'Sweden': 'swe',
 'Malawi': 'mwi',
 'Jamaica': 'jam',
 'Svalbard and Jan Mayen': 'sjm',
 'Turkey': 'tur',
 'Bonaire': 'bonaire',
 'Myanmar': 'mmr',
 'Swaziland': 'swz',
 'Niue': 'niu',
 'China, Macao SAR': 'mac',
 'Colombia': 'col',
 'Sint Maarten (Dutch part)': 'sxm',
 'Georgia': 'geo',
 'Cuba': 'cub',
 'Haiti': 'hti',
 'Tibetan': 'tibetan',
 'Stateless': 'stateless',
 'Liechtenstein': 'lie',
 'Panama': 'pan',
 'Cameroon': 'cmr',
 'Uganda': 'uga',
 'Dem. Rep. of the Congo': 'cod',
 'Various/Unknown': 'various_unknown',
 'Armenia': 'arm',
 'Fiji': 'fji',
 'Western Sahara': 'esh',
 'Samoa': 'wsm',
 'Syrian Arab Rep.': 'syr',
 'Tajikistan': 'tjk',
 'Afghanistan': 'afg',
 'Bermuda': 'bmu',
 'Bhutan': 'btn',
 'Iraq': 'irq',
 'Russian Federation': 'rus',
 'Somalia': 'som',
 "CÃÂ´te d'Ivoire": 'civ',
 'Cyprus': 'cyp',
 'Dominican Rep.': 'dom',
 'Uzbekistan': 'uzb',
 'Solomon Islands': 'slb',
 'American Samoa': 'asm',
 'Poland': 'pol',
 "CÃ´te d'Ivoire": 'civ',
 'Venezuela (Bolivarian Republic of)': 'ven',
 'Tunisia': 'tun',
 'United Kingdom': 'gbr',
 'Belize': 'blz',
 'Brunei Darussalam': 'brn',
 'Guyana': 'guy',
 'Guam': 'gum',
 'Rep. of Moldova': 'mda',
 'Guatemala': 'gtm',
 'Portugal': 'prt',
 'Holy See (the)': 'hos',
 'Costa Rica': 'cri',
 'Wallis and Futuna Islands': 'wlf',
 'Austria': 'aut',
 'Cambodia': 'khm',
 'Uruguay': 'ury',
 'Ukraine': 'ukr',
 'Morocco': 'mar',
 'Indonesia': 'idn',
 'Ethiopia': 'eth',
 'China, Hong Kong SAR': 'hkg',
 'Maldives': 'mdv',
 'United Arab Emirates': 'are',
 'Sierra Leone': 'sle',
 'Estonia': 'est',
 'CuraÃÂ§ao': 'nld_curacao',
 'Sri Lanka': 'lka',
 'Malta': 'mlt',
 'Saint Lucia': 'lca',
 'Mozambique': 'moz',
 'Slovenia': 'svn',
 'Jordan': 'jor',
 'Bolivia (Plurinational State of)': 'bol',
 'Guinea': 'gin',
 'British Virgin Islands': 'vgb',
 'Djibouti': 'dji',
 'Equatorial Guinea': 'gnq',
 'French Polynesia': 'pyf',
 'Australia': 'aus',
 'Gibraltar': 'gib',
 'Ireland': 'irl',
 'Monaco': 'mco',
 'Chile': 'chl',
 'Martinique': 'mtq',
 'Aruba': 'abw',
 'Latvia': 'lva',
 'Spain': 'esp',
 'Seychelles': 'syc',
 'Azerbaijan': 'aze',
 'Niger': 'ner',
 'Tuvalu': 'tuv',
 'Thailand': 'tha',
 'Viet Nam': 'vnm',
 'Nigeria': 'nga',
 'Iran (Islamic Rep. of)': 'irn',
 'Croatia': 'hrv',
 'Suriname': 'sur',
 'Cayman Islands': 'cym',
 'French Guiana': 'guf',
 'France': 'fra',
 'Saudi Arabia': 'sau',
 'Cabo Verde': 'cpv',
 'Philippines': 'phl',
 'Ghana': 'gha',
 'Liberia': 'lbr',
 'Cook Islands': 'cok',
 'Zimbabwe': 'zwe',
 'Burkina Faso': 'bfa',
 'Vanuatu': 'vut',
 'Germany': 'deu',
 'South Sudan': 'ssd',
 'New Zealand': 'nzl',
 'Palestinian': 'pse',
 'Puerto Rico': 'pri',
 'San Marino': 'smr',
 'Rwanda': 'rwa',
 'Libya': 'lby',
 'Belgium': 'bel',
 'Luxembourg': 'lux',
 'Belarus': 'blr',
 'Lesotho': 'lso',
 "Lao People's Dem. Rep.": 'lao',
 'Egypt': 'egy',
 'Switzerland': 'che',
 'Mauritius': 'mus',
 'Guadeloupe': 'glp',
 'Greece': 'grc',
 'Israel': 'isr',
 'Andorra': 'and',
 'Oman': 'omn',
 'Gambia': 'gmb',
 'Montenegro': 'mne',
 'Romania': 'rou',
 'CuraÃ§ao': 'nld_curacao',
 'Mauritania': 'mrt',
 'Grenada': 'grd',
 'Kenya': 'ken',
 'Qatar': 'qat',
 'Kiribati': 'kir',
 'Bangladesh': 'bgd',
 'Peru': 'per',
 'Canada': 'can',
 'Zambia': 'zmb',
 'The former Yugoslav Republic of Macedonia': 'mkd',
 'Angola': 'ago',
 'Czech Rep.': 'cze',
 'Micronesia (Federated States of)': 'fsm'}

In [71]:
data.columns

Index(['Year', 'Country / territory of asylum/residence', 'Origin',
       'Population type', 'Value'],
      dtype='object')

In [72]:
data['Population type'].unique()

array(['Refugees (incl. refugee-like situations)', 'Returned refugees',
       'Internally displaced persons', 'Returned IDPs',
       'Others of concern', 'Asylum-seekers', 'Stateless persons'],
      dtype=object)

In [74]:
pop_type = data['Population type'].unique()

In [75]:
def _conv(s):
    if s == 'Refugees (incl. refugee-like situations)':
        return 'refugees'
    else:
        return to_concept_id(s)

In [76]:
popmap = dict((p, _conv(p)) for p in pop_type)

In [77]:
popmap

{'Refugees (incl. refugee-like situations)': 'refugees',
 'Returned refugees': 'returned_refugees',
 'Internally displaced persons': 'internally_displaced_persons',
 'Returned IDPs': 'returned_idps',
 'Others of concern': 'others_of_concern',
 'Asylum-seekers': 'asylum_seekers',
 'Stateless persons': 'stateless_persons'}

In [78]:
cols = data.columns

In [225]:
data.columns = ['year', 'asylum_residence', 'origin', 'displacement_type', 'displaced_population']

In [226]:
data.head()

,year,asylum_residence,origin,displacement_type,displaced_population
0,1951,Australia,Various/Unknown,Refugees (incl. refugee-like situations),180000.0
1,1951,Austria,Various/Unknown,Refugees (incl. refugee-like situations),282000.0
2,1951,Belgium,Various/Unknown,Refugees (incl. refugee-like situations),55000.0
3,1951,Canada,Various/Unknown,Refugees (incl. refugee-like situations),168511.0
4,1951,"China, Hong Kong SAR",Various/Unknown,Refugees (incl. refugee-like situations),30000.0

In [230]:
# check duplicates

data[data.duplicated(subset=['year', 'asylum_residence', 'origin', 'displacement_type'], keep='first')]

,year,asylum_residence,origin,displacement_type,displaced_population
144796,2014,Serbia and Kosovo (S/RES/1244 (1999)),Algeria,Asylum-seekers,1.0
144798,2014,Serbia and Kosovo (S/RES/1244 (1999)),Bosnia and Herzegovina,Refugees (incl. refugee-like situations),2.0
144802,2014,Serbia and Kosovo (S/RES/1244 (1999)),Croatia,Refugees (incl. refugee-like situations),36.0
144821,2014,Serbia and Kosovo (S/RES/1244 (1999)),Serbia and Kosovo (S/RES/1244 (1999)),Internally displaced persons,17113.0
144823,2014,Serbia and Kosovo (S/RES/1244 (1999)),Serbia and Kosovo (S/RES/1244 (1999)),Returned IDPs,165.0
144830,2014,Serbia and Kosovo (S/RES/1244 (1999)),Syrian Arab Rep.,Refugees (incl. refugee-like situations),1.0
144832,2014,Serbia and Kosovo (S/RES/1244 (1999)),Syrian Arab Rep.,Asylum-seekers,1.0
178072,2017,Serbia and Kosovo (S/RES/1244 (1999)),Bosnia and Herzegovina,Refugees (incl. refugee-like situations),NaN
178078,2017,Serbia and Kosovo (S/RES/1244 (1999)),Croatia,Refugees (incl. refugee-like situations),5.0
178089,2017,Serbia and Kosovo (S/RES/1244 (1999)),Iran (Islamic Rep. of),Asylum-seekers,4.0
178104,2017,Serbia and Kosovo (S/RES/1244 (1999)),Serbia and Kosovo (S/RES/1244 (1999)),Internally displaced persons,201047.0
178106,2017,Serbia and Kosovo (S/RES/1244 (1999)),Serbia and Kosovo (S/RES/1244 (1999)),Returned IDPs,106.0

In [231]:
data[data.duplicated(subset=['year', 'asylum_residence', 'origin', 'displacement_type'], keep='last')]

,year,asylum_residence,origin,displacement_type,displaced_population
144795,2014,Serbia and Kosovo (S/RES/1244 (1999)),Algeria,Asylum-seekers,1.0
144797,2014,Serbia and Kosovo (S/RES/1244 (1999)),Bosnia and Herzegovina,Refugees (incl. refugee-like situations),11323.0
144801,2014,Serbia and Kosovo (S/RES/1244 (1999)),Croatia,Refugees (incl. refugee-like situations),32372.0
144820,2014,Serbia and Kosovo (S/RES/1244 (1999)),Serbia and Kosovo (S/RES/1244 (1999)),Internally displaced persons,206026.0
144822,2014,Serbia and Kosovo (S/RES/1244 (1999)),Serbia and Kosovo (S/RES/1244 (1999)),Returned IDPs,285.0
144829,2014,Serbia and Kosovo (S/RES/1244 (1999)),Syrian Arab Rep.,Refugees (incl. refugee-like situations),5.0
144831,2014,Serbia and Kosovo (S/RES/1244 (1999)),Syrian Arab Rep.,Asylum-seekers,237.0
178071,2017,Serbia and Kosovo (S/RES/1244 (1999)),Bosnia and Herzegovina,Refugees (incl. refugee-like situations),8764.0
178077,2017,Serbia and Kosovo (S/RES/1244 (1999)),Croatia,Refugees (incl. refugee-like situations),19038.0
178088,2017,Serbia and Kosovo (S/RES/1244 (1999)),Iran (Islamic Rep. of),Asylum-seekers,12.0
178103,2017,Serbia and Kosovo (S/RES/1244 (1999)),Serbia and Kosovo (S/RES/1244 (1999)),Internally displaced persons,16406.0
178105,2017,Serbia and Kosovo (S/RES/1244 (1999)),Serbia and Kosovo (S/RES/1244 (1999)),Returned IDPs,87.0

In [232]:
data['asylum_residence'] = data['asylum_residence'].map(countrymapping)

In [233]:
data['asylum_residence'].hasnans

False

In [234]:
data['origin'] = data['origin'].map(lambda x: countrymapping[x.strip()])

In [235]:
data['origin'].hasnans

False

In [236]:
data['displacement_type'] = data['displacement_type'].map(popmap)

In [237]:
data.head()

,year,asylum_residence,origin,displacement_type,displaced_population
0,1951,aus,various_unknown,refugees,180000.0
1,1951,aut,various_unknown,refugees,282000.0
2,1951,bel,various_unknown,refugees,55000.0
3,1951,can,various_unknown,refugees,168511.0
4,1951,hkg,various_unknown,refugees,30000.0

In [238]:
data = data[['asylum_residence', 'origin', 'displacement_type', 'year', 'displaced_population']]

In [239]:
data = data.sort_values(by=['asylum_residence', 'origin', 'displacement_type', 'year'])

In [240]:
data.head()

       asylum_residence origin displacement_type  year  displaced_population
99100               abw    col    asylum_seekers  2010                   1.0
108132              abw    col    asylum_seekers  2011                   3.0
117346              abw    col    asylum_seekers  2012                   5.0
126902              abw    col    asylum_seekers  2013                   4.0
137081              abw    col    asylum_seekers  2014                   4.0

In [241]:
data['displaced_population'] = data['displaced_population'].replace("*", 3)

In [242]:
data = data.dropna(subset=['displaced_population'])

In [243]:
data = data.drop_duplicates(subset=['asylum_residence', 'origin', 'displacement_type', 'year'])

In [244]:
data.to_csv('../../ddf--datapoints--displaced_population--by--asylum_residence--origin--displacement_type--year.csv', index=False)

In [153]:
data2 = data.groupby(['asylum_residence', 'displacement_type', 'year'])['displaced_population'].agg(sum)

In [135]:
data['displaced_population'].dtype

dtype('float64')

In [154]:
data2.head()

asylum_residence  displacement_type  year
abw               asylum_seekers     2010    1.0
                                     2011    4.0
                                     2012    6.0
                                     2013    5.0
                                     2014    5.0
Name: displaced_population, dtype: float64

In [170]:
data2.reset_index().to_csv('../../ddf--datapoints--displaced_population--by--asylum_residence--displacement_type--year.csv', 
                           index=False)

In [176]:
countrydf = pd.DataFrame.from_dict(orient='index', data=countrymapping).reset_index()

In [178]:
countrydf.columns = ['name', 'asylum_residence']

In [180]:
countrydf = countrydf[['asylum_residence', 'name']]

In [181]:
countrydf.to_csv('../../ddf--entities--asylum_residence.csv', index=False)

In [182]:
countrydf.head()

  asylum_residence                                   name
0    serbia_kosovo  Serbia and Kosovo (S/RES/1244 (1999))
1              bih                 Bosnia and Herzegovina
2              zaf                           South Africa
3              ltu                              Lithuania
4              ita                                  Italy

In [183]:
countrydf.columns = ['origin', 'name']

In [184]:
countrydf.to_csv('../../ddf--entities--origin.csv', index=False)

In [187]:
popmap

{'Refugees (incl. refugee-like situations)': 'refugees',
 'Returned refugees': 'returned_refugees',
 'Internally displaced persons': 'internally_displaced_persons',
 'Returned IDPs': 'returned_idps',
 'Others of concern': 'others_of_concern',
 'Asylum-seekers': 'asylum_seekers',
 'Stateless persons': 'stateless_persons'}

In [192]:
poptypedf = pd.DataFrame.from_dict(popmap, orient='index').reset_index()

In [193]:
poptypedf.columns = ['name', 'displacement_type']

In [194]:
poptypedf = poptypedf[['displacement_type', 'name']]

In [195]:
poptypedf

              displacement_type                                      name
0                      refugees  Refugees (incl. refugee-like situations)
1             returned_refugees                         Returned refugees
2  internally_displaced_persons              Internally displaced persons
3                 returned_idps                             Returned IDPs
4             others_of_concern                         Others of concern
5                asylum_seekers                            Asylum-seekers
6             stateless_persons                         Stateless persons

In [196]:
poptypedf.to_csv('ddf--entities--displacement_type.csv', index=False)

In [221]:
concepts = ['asylum_residence', 'origin', 'displacement_type', 'displaced_population', 'year', 'name', 'domain']
cname = ['Country / territory of asylum/residence', 
         'Origin', 'Displacement Type', 'Displaced Population', 'Year', 'Name', 'Domain']
ctype = ['entity_domain', 'entity_domain', 'entity_domain', 'measure', 'time', 'string', 'string']
# cdomain = None

cdf = pd.DataFrame({'concept': concepts, 'name': cname, 'concept_type': ctype})

In [222]:
cdf

,concept,name,concept_type
0,asylum_residence,Country / territory of asylum/residence,entity_domain
1,origin,Origin,entity_domain
2,displacement_type,Displacement Type,entity_domain
3,displaced_population,Displaced Population,measure
4,year,Year,time
5,name,Name,string
6,domain,Domain,string

In [223]:
cdf.to_csv('../../ddf--concepts.csv', index=False)

In [185]:
!open ../../

In [220]:
!ddf create_datapackage --update ../../

backing up previous datapackage.json...
2019-10-14 15:55:03 WARNING no resources or ddfSchema in datapackage.json
2019-10-14 15:55:03 WARNING skipping file .DS_Store
2019-10-14 15:55:03 WARNING skipping file datapackage.json
2019-10-14 15:55:03 WARNING skipping file README.md
2019-10-14 15:55:03 WARNING skipping file .gitignore
2019-10-14 15:55:03 WARNING skipping file .gitattributes
2019-10-14 15:55:03 WARNING skipping file datapackage.json.bak
2019-10-14 15:55:03 INFO generating ddf schema, may take some time...
]0;IPython: etl/notebooks> /Users/semio/src/work/Gapminder/libs/ddf_utils/ddf_utils/model/package.py(195)_gen_entities()
    194             import ipdb; ipdb.set_trace()
--> 195             if concepts[pkey].concept_type == 'entity_domain':
    196                 domain = concepts[pkey].id

0mipdb>                                                                          WARNING: your terminal doesn't support cursor position requests (CPR).
C ?7h0mipdb>                                                                          ipdb>
--KeyboardInterrupt--
C ?7hipdb>
[?2004lipdb>

In [203]:
!validate-ddf --silent ../../

[
  {
    "id": "DATAPACKAGE_INCORRECT_PRIMARY_KEY",
    "type": "Datapackage: Fields section does not contain primary key.",
    "howToFix": "Regenerate or update datapackage as described here: https://github.com/Gapminder/ddf-validation#datapackage",
    "path": "/Users/semio/src/work/Gapminder/datasets/open-numbers/ddf--unhcr--population_statistics/etl/notebooks",
    "data": {
      "reason": "empty ddfSchema section"
    },
    "isWarning": false,
    "tags": [
      "DATAPACKAGE_TAG"
    ]
  },
  {
    "id": "INCONSISTENT_DATAPACKAGE",
    "type": "datapackage.json does not meet \"Data Package\" requirements (https://frictionlessdata.io/specs/data-package/) or some mandatory sections are missing",
    "howToFix": "Fix datapackage.json format in accordance with \"Data Package\" requirements (https://frictionlessdata.io/specs/data-package/) or add mandatory sections (ddfSchema).",
    "path": "/Users/semio/src/work/Gapminder/datasets/open-numbers/ddf--unhcr--population_statistics/etl/notebooks/datapackage.json",
    "data": [
      "Descriptor validation error:\n        Array is too short (0), minimum 1\n        at \"/resources\" in descriptor and\n        at \"/properties/resources/minItems\" in profile"
    ],
    "isWarning": false,
    "tags": [
      "DATAPACKAGE_TAG"
    ]
  },
  {
    "id": "INCONSISTENT_DATAPACKAGE",
    "type": "datapackage.json does not meet \"Data Package\" requirements (https://frictionlessdata.io/specs/data-package/) or some mandatory sections are missing",
    "howToFix": "Fix datapackage.json format in accordance with \"Data Package\" requirements (https://frictionlessdata.io/specs/data-package/) or add mandatory sections (ddfSchema).",
    "path": "/Users/semio/src/work/Gapminder/datasets/open-numbers/ddf--unhcr--population_statistics/etl/notebooks/datapackage.json",
    "data": {
      "reason": "ddfSchema section is missing or invalid"
    },
    "isWarning": false,
    "tags": [
      "DATAPACKAGE_TAG"
    ]
  }
]